### ISSUE TITLE
I got the project working but it won't work.

### ISSUE THREAD

**Issue by Levelheader** [GraxCode/zelixkiller#5]
If I do anything, it errors similar to this

Exception in thread "main" java.lang.Error: Unresolved compilation problems:
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        The type Analyzer is not generic; it cannot be parameterized with arguments <ConstantTracker.ConstantValue>
        The type Analyzer is not generic; it cannot be parameterized with arguments <>
        The type Frame is not generic; it cannot be parameterized with arguments <ConstantTracker.ConstantValue>
        instructions cannot be resolved or is not a field
        The type Frame is not generic; it cannot be parameterized with arguments <ConstantTracker.ConstantValue>
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field
        instructions cannot be resolved or is not a field

        at me.nov.zelixkiller.transformer.zkm11.ControlFlowT11.<init>(ControlFlowT11.java:34)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at me.nov.zelixkiller.ZelixKiller.main(ZelixKiller.java:94)

**Comment by GraxCode** [comment]
Are you sure you are using the right libraries?
